guard 'haml', :input => 'src', :output => 'build' do
  watch %r{^src/.+(\.haml)}
end

guard 'coffeescript', :input => 'src', :output => 'build' do
  watch %r{^src/series/.+(\.coffee)}
end

guard 'sass', :input => 'src', :output => 'build' do
  watch %r{^src/css/.+(\.sass)}
end
